In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import time
import numpy as np
'''
import sys
sys.path.append('Classes')
from arpy import *
'''
import arpa
from tqdm import tqdm
import pickle
import json
import torch


# Input:
### ngram count
### n-1gram count
### unigram count
### prefix count

# Target 
### Pgt


# processing ngram counts

In [ ]:
start = time.time()
file = open('../../2000-2014_ngram_counts.txt','r')

counts = np.zeros(8)

for x in file:
    line = x.split('\t')
    r = line[1].split('\n')
    if (int(r[0]) < 9):
        counts[int(r[0])-1] += 1
        
print('amount of ngrams occuring r times:')
print(counts)
end = time.time()
print('time:' + str(end-start))

In [ ]:
plt.plot(counts[1:10])

In [ ]:
start = time.time()
file = open('../../2000-2014_ngram_counts.txt','r')

totals = np.zeros(3)
ngrams = 0

for x in file:
    line = x.split('\t')
    tuple_size = len(line[0].split(' '))

    r = line[1].split('\n')
    totals[tuple_size-1] = totals[tuple_size-1] + int(r[0])

    ngrams += 1

print('sum of ngrams counts:')
print(totals)
print('total unique ngrams:')
print(ngrams)
end = time.time()
print('time: ' + str(end-start))

# testing on smaller sets

In [ ]:
start = time.time()
file = open('../../GTBO_LM.lm','r')
#file = open('../../lm','r')


total = 0
ngrams = 0

for x in range(5):
    file.readline()

for x in file:
    line = x.split('\t')
    if line[0] != '\n':
        if line[0] != '':
            if line[0][0] != '\\':
                #log = float(line[0])
                #total = total + 10**log
                #print('\ntotal: ' + str(total))
                #print(10**log)
                ngrams+=1
    
print(ngrams)
end = time.time()
print('time: ' + str(end-start))

In [ ]:
start = time.time()
file = open('../../count.txt','r')

totals = np.zeros(3)
ngrams = 0

for x in file:
    line = x.split('\t')
    tuple_size = len(line[0].split(' '))
    r = line[-1].split('\n')
    totals[tuple_size-1] = totals[tuple_size-1] + int(r[0])
    ngrams += 1
    
print(totals)
print(ngrams)
end = time.time()
print('time: ' + str(end-start))

# python arpa file 

In [ ]:
lm = arpa.loadf('../../round1/practiseLM.arpa')
#ABOUT CERTAIN AREAS

# Pgt calculated by srilm

In [ ]:
print('Pgt(' + str(lm[0].p("ABOUT CERTAIN AREAS")) + ')')

### get discount factors from srilm output

In [ ]:
gtdc = open('../../round1/practise_gt_dc.txt','r')
dc = np.zeros(7)

gtdc.readline()
gtdc.readline()

for x in range(7):
    line = gtdc.readline()
    line = line.split(' ')[2].split('\n')[0]
    dc[x] = float(line)
    
print('discount factor for r = 1, 2, 3, 4, 5, 6, 7')
print(dc)

# Prf - calculated by hand

In [ ]:
start = time.time()
file = open('../../round1/2000counts.txt','r')

trigram = 0
bigrams = 0

for x in file:
    #line = file.readline()
    #line = line.split('\t')
    line = x.split('\t')
    tuple_size = len(line[0].split(' '))
    
    ngram = line[0]
    r = line[-1].split('\n')[0]

    if ngram == 'ABOUT CERTAIN AREAS':
        trigram = r
    if ngram == 'ABOUT CERTAIN':
        bigram = r
        
    '''
    print(ngram)
    print('tuple size: ' + str(tuple_size))
    print('count: ' + str(r))
    '''

print('trigram count: '+ trigram)
print('bigram count: ' + bigram)
prf = float(trigram)/float(bigram)
print('Prf(' + str(prf) +')')

end = time.time()
print('time: ' + str(end-start))

print('Pgt(' + str(prf*dc[int(trigram)-1]) + ')')

# NB! Pgt = discountfactor(r) * Prf

# Find ngrams with r > 7

In [ ]:
start = time.time()
file = open('../../round1/2000counts.txt','r')

trigram = 0
bigrams = 0

for x in range(1000):
    line = file.readline()
    line = line.split('\t')
    #line = x.split('\t')
    tuple_size = len(line[0].split(' '))
    
    ngram = line[0]
    r = line[-1].split('\n')[0]

    if tuple_size == 3 and int(r) > 7:
        print(ngram)
        
        
    '''
    print(ngram)
    print('tuple size: ' + str(tuple_size))
    print('count: ' + str(r))
    '''

end = time.time()
print('time: ' + str(end-start))

# AS seen below, for r > Pgt = Prf

In [ ]:
print('Pgt(' + str(lm[0].p(".CO .ZA </s>"))+ ')')

In [ ]:
start = time.time()
file = open('../../round1/2000counts.txt','r')

trigram = 0
bigrams = 0

for x in file:
    #line = file.readline()
    #line = line.split('\t')
    line = x.split('\t')
    tuple_size = len(line[0].split(' '))
    
    ngram = line[0]
    r = line[-1].split('\n')[0]

    if ngram == '.CO .ZA </s>':
        trigram = r
    if ngram == '.CO .ZA':
        bigram = r
        
    '''
    print(ngram)
    print('tuple size: ' + str(tuple_size))
    print('count: ' + str(r))
    '''

print('trigram count: '+ trigram)
print('bigram count: ' + bigram)
prf = float(trigram)/float(bigram)
print('Prf(' + str(prf) +')')

end = time.time()
print('time: ' + str(end-start))

# Read counts from file, VERY INEFFECTIVE

In [45]:
num_lines = sum(1 for line in open('../../round1/2000counts.txt','r'))
#num_lines = sum(1 for line in open('../../count.txt','r'))

print(num_lines)

9672425


In [ ]:
start = time.time()
file = '../../round1/2000counts.txt'
#file = '../../count.txt'
first_read = open(file ,'r')
#second_read = open(file,'r')


count = 0

for x in tqdm(first_read, total=num_lines):

    line = x.split('\t')
    ngram = line[0].split(' ')
    tuple_size = len(ngram)
    r = int(line[-1])
    
    if tuple_size == 2:
        prefix_count = r
    
    if tuple_size == 3 and r < 8:
        #count += 1
        #print('\n' + ngram[0] +' '+ ngram[1]+' ' + ngram[2] + '\t' + str(r))
        #print(ngram[0] + ' '+ ngram[1] +'\t' + str(prefix_count))
        #print('\n'+line[0])
        #print(r)
                
        prefix = ngram[0] + ' ' + ngram[1]
        bigram = ngram[1] + ' ' + ngram[2]
                
        
        found_bigram = 0
        found_unigram = 0
        '''
        for y in second_read:
            
            if y[0] == ngram[1][0]:
                line2 = y.split('\t')
                tuple_size = len(line2[0].split(' '))
                r_2 = int(line2[-1])

                if bigram == line2[0]:
                    found_bigram = 1
                    #print(line2[0] + '\t' + str(r_2))
                    if found_unigram == 1:
                        break
                    
            if y[0] == ngram[2][0]:
                
                line2 = y.split('\t')
                tuple_size = len(line2[0].split(' '))
                r_2 = int(line2[-1])
                
                if ngram[2] == line2[0]:
                    found_unigram = 1
                    #print(line2[0] + '\t' + str(r_2))
                    if found_bigram == 1:
                        break
        '''



print(count)
end = time.time()
print('time: ' + str(end-start))

# Read counts into dictionary first

In [2]:
#start = time.time()
#file = '../../counts/2000counts.txt'
#file = '../../counts/08_14counts.txt'
#file = '../../counts/12_14counts.txt'
file = '../../counts/dev_counts.txt'

first_read = open(file ,'r')

num_lines = sum(1 for line in open(file,'r'))
#print(num_lines)

ngram_dict = {}
for x in tqdm(first_read, total=num_lines):
    line = x.split('\t')
    r = int(line[-1])
    ngram_dict[line[0]] = r

#print(ngram_dict['H. I. V.'])
#end = time.time()
#print('time: ' + str(end-start))

100%|██████████| 15718800/15718800 [00:15<00:00, 1022245.59it/s]


# setup tensor

### get discount factors from srilm output

In [3]:
#gtdc = open('../../counts/gtdc_factors_08-14.txt','r')
#gtdc = open('../../counts/gtdc_factors_2000.txt','r')
#gtdc = open('../../counts/gt3dc_12-14.txt','r')
gtdc = open('../../counts/gt3dc_dev.txt','r')

dc = np.zeros(7)

gtdc.readline()
gtdc.readline()

for x in range(7):
    line = gtdc.readline()
    line = line.split(' ')[2].split('\n')[0]
    dc[x] = float(line)
    
print('discount factor for r = 1, 2, 3, 4, 5, 6, 7')
print(dc)

discount factor for r = 1, 2, 3, 4, 5, 6, 7
[0.328853 0.496574 0.643644 0.669976 0.773884 0.797639 0.842846]


# check cuda


In [4]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())

if device.type == 'cuda':
    #print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**2,1), 'MB')
    print('Cached:   ', round(torch.cuda.memory_cached(0)/1024**2,1), 'MB')

GeForce GTX 1060 6GB
True
Memory Usage:
Allocated: 0.0 MB
Cached:    0.0 MB


# Load Trigram Counts to tensor

In [5]:
#start = time.time()
#file = '../../counts/08_14counts.txt'
#file = '../../counts/2000counts.txt'
#file = '../../counts/12_14counts.txt'
file = '../../counts/dev_counts.txt'


first_read = open(file ,'r')

num_lines = sum(1 for line in open(file,'r'))
#print(num_lines)
num_trigrams = 0

for x in tqdm(first_read, total=num_lines):
    line = x.split('\t')
    r = int(line[-1])
    ngram = line[0].split(' ')
    tuple_size = len(ngram)

    if tuple_size == 3 and r < 8 and r!= 1:
        num_trigrams += 1
        
print(num_trigrams)
end = time.time()
#print('time: ' + str(end-start))

100%|██████████| 15718800/15718800 [00:14<00:00, 1056147.82it/s]

2648573


# instantiate tensors on gpu

In [6]:
#inputs = data[0].to(device)
inputs = torch.zeros(4,num_trigrams, dtype=torch.float, device = device)
print(inputs)
outputs = torch.zeros(1,num_trigrams, dtype=torch.float, device = device)
print(outputs)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')


In [24]:
#print(ngram_dict["\' A P."])

# fill tensors

In [7]:
start = time.time()
#file = '../../counts/08_14counts.txt'
#file = '../../counts/2000counts.txt'
#file = '../../counts/12_14counts.txt'
file = '../../counts/dev_counts.txt'


first_read = open(file ,'r')

num_lines = sum(1 for line in open(file,'r'))
#print(num_lines)
count = 0

for x in tqdm(first_read, total=num_lines):
    line = x.split('\t')
    r = int(line[-1])
    ngram = line[0].split(' ')
    tuple_size = len(ngram)
    
    if tuple_size == 3 and r < 8 and r!= 1:
        inputs[0][count] = ngram_dict[ngram[0] + ' ' + ngram[1]]  #prefix count
        inputs[1][count] = ngram_dict[line[0]]                    #trigram count
        inputs[2][count] = ngram_dict[ngram[1] + ' ' + ngram[2]]  #backoff bigram count
        inputs[3][count] = ngram_dict[ngram[2]]                   #unigram count
        
        #Pgt = Prf * dc_factor
        outputs[0][count] = (inputs[1][count]/inputs[0][count]) * dc[r-1]    
        count += 1
        
end = time.time()
print('time: ' + str(end-start))

100%|██████████| 15718800/15718800 [09:11<00:00, 28486.48it/s]

time: 552.9847664833069


In [8]:
print(inputs)
print(inputs.size())
print(outputs)
print(outputs.size())

tensor([[2.0000e+00, 3.0000e+00, 2.0000e+00,  ..., 3.0000e+00, 5.0000e+00,
         2.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00,  ..., 2.0000e+00, 2.0000e+00,
         2.0000e+00],
        [3.2100e+02, 3.1100e+02, 2.1460e+03,  ..., 2.0000e+00, 5.0000e+00,
         5.4752e+04],
        [1.7450e+04, 2.4549e+04, 4.9295e+04,  ..., 7.0853e+05, 1.3115e+05,
         1.5283e+06]], device='cuda:0')
torch.Size([4, 2648573])
tensor([[0.4966, 0.3310, 0.4966,  ..., 0.3310, 0.1986, 0.4966]],
       device='cuda:0')
torch.Size([1, 2648573])


# saving (and loading) tensors using pytorch

In [9]:
torch.save(inputs, '../../pickles/input_' + str(num_trigrams) +'_dev_file')
torch.save(outputs, '../../pickles/output_' + str(num_trigrams) +'_dev_file')

In [ ]:
device = torch.device("cuda")
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.to(device)