# Neural Net Exercise
## Basic pytorch matrix functions:


In [47]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x = torch.zeros(2,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0]])


In [8]:
x = x.new_ones(3,3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.tensor([[3, 2],[5,6]])
print(x)

tensor([[3, 2],
        [5, 6]])


In [12]:
print(x.size()) #returns tuple (y,x)

torch.Size([2, 2])


In [14]:
print(len(x.size()))

2


In [16]:
print(x.size()[0])

2


# Numpy cross compatibility

In [18]:
# convert tensor to np
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
#convert np to tensor
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [24]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## Cuda implementation


In [25]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[4, 3],
        [6, 7]], device='cuda:0')
tensor([[4., 3.],
        [6., 7.]], dtype=torch.float64)


In [53]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Assuming that we are on a CUDA machine, this should print a CUDA device:

print(device)

cuda:0


In [55]:
net.to(device)

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [43]:
inputs, labels = data[0].to(device), data[1].to(device)